name: quadratic_equation
description: A sample command-line application -> Quadratic Equation.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
